### ISSUE TITLE
Fix crash bug reported in cerification report

### ISSUE THREAD

**Issue by rapuke** [UABS-ISOM/aroaro#56]

**Comment by crookm** [comment]
### Solution
* Build using the MRTK build window (`Mixed Reality Toolkit -> Build window`)
* Under `Unity Build Options`, make sure `Unity C# Projects` is UN-checked
* Under `Appx Build Options`, set the **scripting backend** to `IL2CPP`, the **build configuration** to `Master`, the **build platform** to `x64`, and then select `Build APPX`
* This takes a long time
* When finished, browse to the output directory, and right-click and run in powershell the ps1 script, to install and trust the app
* Open WACK and test as normal

All should come back as passed.
